openapi: 3.0.2
info:
  version: '1.0'
  title: 'OpenApi'
  description: Specification for openapi
  termsOfService: http://terms.example.com
  contact:
    name: Example Name
    url: example@example.com
    email: example@mail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/liscence/LISCENCE-2.0.html
servers: 
  - url: http://localhost:9999
    description: Development server
  - url: http://localhost:9991
    description: QA server
  - url: http://localhost:9999
    description: Production server
paths:
  /v1/customers: 
    get:
      responses:
        '200':
          description: List of customers  
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 10
                description: Lis tof customers
                items:
                  type: object
                  description: Customer object
                  properties:
                    id:
                      type: string
                      format: uuid
                    firstName:
                      type: string
                      minLength: 2
                      maxLength: 100
                      example: FirstName
                    lastName:
                      type: string
                      minLength: 2
                      maxLength: 100
                      example: LastName
                    address:
                      type: object
                      properties:
                        street:
                          type: string
                        city:
                          type: string
                        stateCode:
                          type: string
                          minLength: 2
                          maxLength: 2
                          enum: [AL, AK, AZ, AR, CA]
                          description: state code
                        zipCode:
                          type: string
                          
                        
    put:
      responses:
        '200':
          description: List of custimers
  /get:
    get:
      responses:
        '200':
          description: Get message
